services:
  - type: web
    name: libraryrevamp-web
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: LibraryRevamp
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: libraryrevamp-db
          property: connectionString
      - key: DB_SCHEMA
        value: libraryrevamp
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database

databases:
  - name: libraryrevamp-db
    databaseName: library
    user: library_user
    plan: free
    region: singapore
    ipAllowList: []
